version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6

    steps:

      - checkout

      - run:
          name: Zip Artifact
          command: |
            echo "testing the current build number: ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p artifacts
            pwd
            ls -al
            zip -r serverless.zip lambda_func.py

      - run:
          name: Artifacts are being uploded to S3
          command: |
            sudo pip install awscli
            aws s3 cp serverless.zip s3://${BUCKET_NAME}


      - run:
          command: |
            touch 777 lambda.txt
            echo "Update the function"
            aws lambda update-function-code --function-name  handler_name  --s3-bucket ${BUCKET_NAME} --s3-key serverless.zip --region ${AWS_REGION} > lambda.txt
          name: Update the function



workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master